// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAlertFields {
  /** alert */
  alert?: string | undefined;
}

export interface IAlert extends Entry<IAlertFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "alert";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAwardsFields {
  /** Фотография */
  image?: Asset | undefined;

  /** Заголовок */
  title?: string | undefined;

  /** Победители (золото) */
  gold?: string | undefined;

  /** Призеры (серебро) */
  silver?: string | undefined;

  /** Призёры (бронза) */
  bronze?: string | undefined;

  /** Участники */
  part?: string | undefined;

  /** Дата */
  date?: string | undefined;
}

export interface IAwards extends Entry<IAwardsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "awards";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IContactsFields {
  /** Время работы */
  time?: string | undefined;

  /** Дни работы */
  days?: string[] | undefined;
}

export interface IContacts extends Entry<IContactsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "contacts";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IContactsNamesFields {
  /** Должность */
  type?: string | undefined;

  /** Имя */
  name?: string | undefined;

  /** Телефон */
  number?: string | undefined;

  /** Почта */
  mail?: string | undefined;
}

export interface IContactsNames extends Entry<IContactsNamesFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "contactsNames";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEventsFields {
  /** Название события */
  title?: string | undefined;

  /** Место проведения */
  place?: string | undefined;

  /** Дата */
  date?: string | undefined;
}

export interface IEvents extends Entry<IEventsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "events";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IGroupsFields {
  /** Картинка */
  image?: Asset | undefined;

  /** Заголовок */
  title?: string | undefined;

  /** Тренер. Должность */
  type?: string | undefined;

  /** Тренер. ФИО */
  name?: string | undefined;

  /** Занятие 1. День недели */
  day1?: string | undefined;

  /** Занятие 1. Время занятия */
  time1?: string | undefined;

  /** Занятие 2. День недели */
  day2?: string | undefined;

  /** Занятие 2. Время занятия */
  time2?: string | undefined;

  /** Занятие 3. День недели */
  day3?: string | undefined;

  /** Занятие 3. Время занятия */
  time3?: string | undefined;
}

export interface IGroups extends Entry<IGroupsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "groups";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMainPageFields {
  /** Заголовок */
  mainTitle?: Document | undefined;

  /** Подзаголовок */
  mainSubtitile?: string | undefined;
}

export interface IMainPage extends Entry<IMainPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "mainPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMainSliderFields {
  /** Заголовок */
  titile?: string | undefined;

  /** Подзаголовок */
  subtitle?: string | undefined;

  /** Ссылка */
  link?: string | undefined;

  /** Картинка */
  image?: Asset | undefined;
}

export interface IMainSlider extends Entry<IMainSliderFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "mainSlider";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INewsFields {
  /** newsImage */
  newsImage?: Asset | undefined;

  /** title */
  title?: string | undefined;

  /** text */
  text?: Document | undefined;
}

export interface INews extends Entry<INewsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "news";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStaffFields {
  /** Фотграфия */
  image?: Asset | undefined;

  /** Должность */
  type?: string | undefined;

  /** ФИО */
  name?: string | undefined;

  /** Описание */
  text?: string | undefined;
}

export interface IStaff extends Entry<IStaffFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "staff";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "alert"
  | "awards"
  | "contacts"
  | "contactsNames"
  | "events"
  | "groups"
  | "mainPage"
  | "mainSlider"
  | "news"
  | "staff";

export type IEntry =
  | IAlert
  | IAwards
  | IContacts
  | IContactsNames
  | IEvents
  | IGroups
  | IMainPage
  | IMainSlider
  | INews
  | IStaff;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
