import Header from '@/components/Header'
import Head from 'next/head'
import React from 'react'

export default function Trainings() {
  return (
    <>
      <div className="page-wrapper">
        <Head>
          <title>Бокс МИСИС</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <Header/>
        <main>
          <div className="container">
            
          </div>
        </main>
      </div>
    </>
  )
}
