import Header from '@/components/Header'
import { getTrainings } from '@/utils';
import Head from 'next/head'
import React from 'react'
import { IVariants, IVariantsFields } from '../../../contentful';
import styles from '@/styles/Trainings.module.scss';
import TrainingItem from '@/components/TrainingItem';

export default function Trainings({trainings}: {trainings: Array<IVariants>}) {

  return (
    <>
      <div className="page-wrapper">
        <Head>
          <title>Бокс МИСИС</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <Header/>
        <main>
          <div className="container">
            <h1 className="page__title">Тренировки</h1>
            <div className={styles.trainings}>
              {trainings.map((item) => 
                <TrainingItem key={item.sys.id} item={item.fields}/>
              )}
            </div>
          </div>
        </main>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const variants = await getTrainings();
  return {
      props: {
        trainings: variants,
      }
  }
}