import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import MainSlider from '@/components/MainSlider'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Бокс МИСИС</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <MainSlider/>
      </main>
    </>
  )
}
