import Head from 'next/head'
import Header from '@/components/Header'
import MainSlider, { ISlide } from '@/components/MainSlider'
import { getMainSlides } from '@/utils'

export default function Home({slides}: {slides: Array<ISlide>}) {
  return (
    <>
      <div className="wrapper">
        <Head>
          <title>Бокс МИСИС</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <Header/>
        <main>
          <MainSlider slides={slides}/>
        </main>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const slides = await getMainSlides();
  return {
      props: {
          slides: slides,
      }
  }
}